-- Detailed permissions: module → page → action (ingredients.delete, purchases.approve…), replacing the first
-- version's one-permission-per-module list. Enforced per endpoint in the API (lib/rbac.ts is the catalog).
--
--   Workspace roles are converted so each keeps exactly what it could do: every old permission becomes the pages and
--   actions it used to open, and the old "base data is always visible" rule (catalog:read) is written in explicitly.
--   Implied needs (an action needs its page) are added by the API when the role is read.

ALTER TABLE tenant_roles DROP CONSTRAINT IF EXISTS tenant_roles_permissions_check;

WITH legacy(old, new) AS (VALUES
    ('catalog:read','ingredients.view'),
    ('catalog:read','ingredients.export'),
    ('catalog:read','suppliers.view'),
    ('catalog:read','branches.view'),
    ('catalog:read','locations.view'),
    ('catalog:read','units.view'),
    ('catalog:read','settings.view'),
    ('catalog:write','ingredients.create'),
    ('catalog:write','ingredients.edit'),
    ('catalog:write','ingredients.delete'),
    ('catalog:write','ingredients.import'),
    ('catalog:write','suppliers.create'),
    ('catalog:write','suppliers.edit'),
    ('catalog:write','suppliers.delete'),
    ('catalog:write','branches.create'),
    ('catalog:write','branches.edit'),
    ('catalog:write','branches.delete'),
    ('catalog:write','locations.create'),
    ('catalog:write','locations.edit'),
    ('catalog:write','locations.delete'),
    ('catalog:write','dining.create'),
    ('catalog:write','dining.edit'),
    ('catalog:write','platforms.create'),
    ('catalog:write','platforms.edit'),
    ('stock:read','stock.view'),
    ('stock:read','batches.view'),
    ('stock:read','transfers.view'),
    ('stock:read','waste.view'),
    ('stock:read','stocktakes.view'),
    ('stock:read','movements.view'),
    ('stock:adjust','batches.create'),
    ('stock:adjust','transfers.create'),
    ('stock:adjust','transfers.dispatch'),
    ('stock:adjust','transfers.receive'),
    ('stock:adjust','transfers.cancel'),
    ('stock:adjust','waste.create'),
    ('stock:adjust','stocktakes.count'),
    ('stock:adjust','prep_recipes.produce'),
    ('stock:post_count','stocktakes.post'),
    ('purchases:read','requisitions.view'),
    ('purchases:read','purchases.view'),
    ('purchases:read','goods_receipts.view'),
    ('purchases:read','purchase_returns.view'),
    ('purchases:read','payables.view'),
    ('purchases:write','requisitions.create'),
    ('purchases:write','requisitions.cancel'),
    ('purchases:write','requisitions.convert'),
    ('purchases:write','purchases.create'),
    ('purchases:approve','requisitions.approve'),
    ('purchases:approve','purchases.approve'),
    ('purchases:approve','purchases.cancel'),
    ('purchases:approve','purchases.close'),
    ('purchases:receive','goods_receipts.create'),
    ('purchases:receive','purchase_returns.create'),
    ('payables:write','payables.pay'),
    ('payables:write','expenses.pay'),
    ('recipes:read','recipes.view'),
    ('recipes:read','prep_recipes.view'),
    ('recipes:read','modifiers.view'),
    ('recipes:write','recipes.create'),
    ('recipes:write','recipes.edit'),
    ('recipes:write','recipes.delete'),
    ('recipes:write','recipes.approve'),
    ('recipes:write','prep_recipes.create'),
    ('recipes:write','prep_recipes.edit'),
    ('recipes:write','modifiers.create'),
    ('recipes:write','modifiers.edit'),
    ('pos:read','customers.view'),
    ('pos:read','shifts.view'),
    ('pos:read','orders.view'),
    ('pos:read','dining.view'),
    ('pos:read','platforms.view'),
    ('pos:operate','pos.sell'),
    ('pos:operate','customers.create'),
    ('pos:operate','customers.edit'),
    ('pos:refund','orders.refund'),
    ('pos:refund','pos.void'),
    ('pos:refund','pos.supervise'),
    ('pos:discount_override','pos.discount'),
    ('pos:kitchen','kitchen.use'),
    ('reports:read','rep_daily_sales.view'),
    ('reports:read','rep_sales_channel.view'),
    ('reports:read','rep_cashier.view'),
    ('reports:read','rep_vat.view'),
    ('reports:read','rep_ideal_actual.view'),
    ('reports:read','rep_menu_profit.view'),
    ('reports:read','rep_menu_eng.view'),
    ('reports:read','rep_stock_turnover.view'),
    ('reports:read','rep_supplier_perf.view'),
    ('reports:read','rep_recipe_explosion.view'),
    ('reports:read','rep_purchase_prices.view'),
    ('reports:read','rep_stock_valuation.view'),
    ('reports:read','rep_waste.view'),
    ('reports:read','rep_stock_variance.view'),
    ('reports:read','rep_expenses.view'),
    ('expenses:read','expenses.view'),
    ('expenses:write','expenses.create'),
    ('expenses:write','expenses.cancel'),
    ('expenses:write','expenses.categories'),
    ('expenses:approve','expenses.approve'),
    ('members:manage','members.view'),
    ('members:manage','members.invite'),
    ('members:manage','members.edit'),
    ('members:manage','roles.view'),
    ('settings:manage','settings.edit'),
    ('settings:manage','billing.view'),
    ('settings:manage','billing.pay'),
    ('settings:manage','zatca.onboard'),
    ('settings:manage','gateways.manage'),
    ('settings:manage','acc_settings.tax_profile'),
    ('assistant:use','assistant.use'),
    ('accounting:read','acc_overview.view'),
    ('accounting:read','acc_invoices.view'),
    ('accounting:read','acc_receipts.view'),
    ('accounting:read','acc_journal.view'),
    ('accounting:read','acc_accounts.view'),
    ('accounting:read','acc_reports.view'),
    ('accounting:read','zatca.view'),
    ('accounting:read','gateways.view'),
    ('accounting:read','acc_settings.view'),
    ('accounting:write','acc_invoices.create'),
    ('accounting:write','acc_receipts.create'),
    ('accounting:write','acc_journal.create'),
    ('accounting:write','acc_journal.reverse'),
    ('accounting:write','zatca.submit'),
    ('accounting:manage','acc_accounts.create'),
    ('accounting:manage','acc_accounts.edit'),
    ('accounting:manage','acc_settings.manage')
)
UPDATE tenant_roles r SET permissions = (
  SELECT array_agg(DISTINCT l.new ORDER BY l.new) FROM legacy l WHERE l.old = ANY(r.permissions || ARRAY['catalog:read'])
) WHERE EXISTS (SELECT 1 FROM unnest(r.permissions) p WHERE p LIKE '%:%');

-- The names themselves are checked by the API against the catalog; the database keeps the shape honest.
ALTER TABLE tenant_roles ADD CONSTRAINT tenant_roles_permissions_check CHECK (
  cardinality(permissions) BETWEEN 1 AND 500
  AND array_to_string(permissions, ',') ~ '^[a-z_]+\.[a-z_]+(,[a-z_]+\.[a-z_]+)*$'
);
