// Regenerates apps/web/src/api/permissions.ts from the server catalog (lib/rbac.ts). The API test
// "web permission list matches the server" fails until this is run after a catalog change.
import { writeFileSync } from "node:fs";
import { PERMISSIONS } from "../lib/rbac.ts";

const lines: string[] = [];
for (let i = 0; i < PERMISSIONS.length; i += 6) lines.push(`  ${PERMISSIONS.slice(i, i + 6).map((p) => JSON.stringify(p)).join(", ")},`);
const out = `// The permission names the server enforces (apps/api/src/lib/rbac.ts, page.action). A test in the API keeps
// this list identical to the server's; labels and the module → page tree come from GET /t/roles.
// Generated by \`npm run gen:permissions\` (apps/api): do not edit by hand.
export const PERMISSIONS = [
${lines.join("\n")}
] as const;
export type Permission = (typeof PERMISSIONS)[number];
`;
writeFileSync(new URL("../../../web/src/api/permissions.ts", import.meta.url), out);
console.log(`${PERMISSIONS.length} permissions written`);
